service: celsus-contacts

plugins:
  - serverless-python-requirements # For python dependencies packaging
  - serverless-domain-manager

custom:
  config: ${file(./infra.json)}
  pythonRequirements: # For python dependencies packaging
    dockerizePip: true
    slim: true
  customDomain:
    domainName: "api-celsus.isnan.eu"
    certificateName: ${self:custom.config.certificate}
    hostedZoneId: ${self:custom.config.hostedZone}
    basePath: "contacts"
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: edge

provider:
  name: aws
  runtime: python3.8
  versionFunctions: false
  memorySize: 1024
  region: ${self:custom.config.region}
  stage: ${self:custom.config.environment}
  endpointType: EDGE
  profile: serverless-admin-profile
  timeout: 30
  # >>> Enable Gzip compression on AWS APi Gateway
  apiGateway:
    minimumCompressionSize: 1024 # in bytes
  # <<< Enable Gzip compression on AWS APi Gateway
  # >>> Lambda has to live in VPC in order to access RDS
  role: ${self:custom.config.lambdaExecutionRoleArn}
  vpc:
    securityGroupIds:
      - ${self:custom.config.coreStorageSecurityGroup} # To access the RDS instance
      - ${self:custom.config.mainVPCDefaultSecurityGroup} # To publish to SNS via the VPC Endpoint
    subnetIds:
      - ${self:custom.config.mainVPCSubnet2}
  # <<< Lambda has to live in VPC in order to access RDS

  environment:
    PGUSER: ${ssm:contact_storage_username_${self:provider.stage}~true}
    PGPASSWORD: ${ssm:contact_storage_password_${self:provider.stage}~true}
    PGHOST: ${ssm:contact_storage_hostname_${self:provider.stage}~true}
    PGPORT: ${ssm:contact_storage_port_${self:provider.stage}~true}
    PGDATABASE: ${ssm:contact_storage_database_${self:provider.stage}~true}
    PGSCHEMA: ${ssm:contact_storage_schema_${self:provider.stage}~true}
    REGION: ${self:custom.config.region}
    LOG_LEVEL: info

package:
  exclude:
    - .vscode/**
    - .travis.yml
    - package.json
    - package-lock.json
    - node_modules/**
    - tests/**
    - conftest.py
    - pytest.ini

functions:
  postContact:
    handler: contacts/handler.post_contact
    name: post-contact
    events:
      - http:
          path: v1/contacts
          method: post
          cors: true
          authorizer:
            arn: ${self:custom.config.userPoolArn}

  getContacts:
    handler: contacts/handler.get_contacts
    name: get-contacts
    events:
      - http:
          path: v1/contacts
          method: get
          cors: true
          authorizer:
            arn: ${self:custom.config.userPoolArn}
  deleteContact:
    handler: contacts/handler.delete_contact
    name: delete-contact
    events:
      - http:
          path: v1/contacts/{id}
          method: delete
          cors: true
          authorizer:
            arn: ${self:custom.config.userPoolArn}

  handleMessages:
    handler: contacts/handler.handle_messages
    name: handle-contacts-messages
    events:
      - sqs:
          arn: ${self:custom.config.contactsQueueArn}
          batchSize: 1
